[{"question": "How many zeros are there in a googol?", "answers":["100", "10", "1,000", "1,000,000"], "answer": "100"},
{"question": "What is the Roman numeral for 500?", "answers":["D", "L", "X", "C"], "answer": "D"},
{"question": "What are the first 6 digits of the number &quot;Pi&quot;", "answers":["3.14159", "3.14169", "3.12423", "3.25812"], "answer": "3.14159"},
{"question": "What is the alphanumeric representation of the imaginary number?", "answers":["i", "e", "n", "x"], "answer": "i"},
{"question": "In the hexadecimal system, what number comes after 9?", "answers":["The letter A", "10", "The number 0", "16"], "answer": "The letter A"},
{"question": "To the nearest whole number, how many radians are in a whole circle?", "answers":["6", "3", "4", "5"], "answer": "6"},
{"question": "What Greek letter is used to signify summation?", "answers":["Sigma", "Delta", "Alpha", "Omega"], "answer": "Sigma"},
{"question": "What is an angle called if it is greater than 90 degrees", "answers":["Obtuse", "Acute", "Straight", "Right"], "answer": "Obtuse"},
{"question": "What number does a giga stand for?", "answers":["A billion", "A trillion", "A million", "A quadrillion"], "answer": "A billion"},
{"question": "How many equal sides do Icosahedrons have?", "answers":["20", "30", "15", "25"], "answer": "20"}]