[{"question": "What was the first living creature in space?", "answers":["Fruit Flies", "Monkey", "Dog", "Mouse"], "answer": "Fruit Flies"},
{"question": "Which element has the atomic number of 7?", "answers":["Nitrogen", "Oxygen", "Hydrogen", "Neon"], "answer": "Nitrogen"},
{"question": "Who developed the first successful polio vaccine in the 1950s?", "answers":["Jonas Salk", "John F. Enders", "Thomas Weller", "Frederick Robbins"], "answer": "Jonas Salk"},
{"question": "The human right lung has how many lobes?", "answers":["3", "4", "2", "1"], "answer": "3"},
{"question": "What is the unit of electrical capacitance?", "answers":["Farad", "Gauss", "Henry", "Watt"], "answer": "Farad"},
{"question": "What part of the brain takes its name from the Greek for seahorse?", "answers":["Hippocampus", "Cerebellum", "Thalamus", "Amygdala"], "answer": "Hippocampus"},
{"question": "What term is best asscociated with Sigmund Freud?", "answers":["Psychoanalysis", "Cognitive-Behavioral Therapy", "Theory of Gravity", "Dialectical Behavior Therapy"], "answer": "Psychoanalysis"},
{"question": "Myopia is the scientific term for which condition?", "answers":["Shortsightedness", "Farsightedness", "Double Vision", "Clouded Vision"], "answer": "Shortsightedness"},
{"question": "Which color cannot be produced in roses, even through genetic alteration?", "answers":["Blue", "Black", "Orange", "Brown"], "answer": "Blue"},
{"question": "What are the smallest blood vessels in the human body?", "answers":["Capillaries", "Arterioles", "Veinules", "Lymphatics"], "answer": "Capillaries"}]